---
title: "Homework: CAS and PubChem Chemical Descriptors (Draft)"
author: ""
date: "Due September 21, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please complete the following tasks; hopefully you'll be able to complete this homework assignment under an hour. Please see the accompanying *Handout: CAS and PubChem Chemical Descriptors* for notes on both the `R` coding and chemsitry needed/discussed in this assignement. 

## Tasks

On the Quercus course webpage: 

1. Obtain your unique, individually assigned, chemical pollutant by complete the *Random Chemical Assignment* quiz on Quercus. This isn't worth any points, it'll simply assigne you a chemical. 

Using R in R Studio:

2. Create a `data.frame` that includes your unique chemical and the six PFAS compounds in the `ExamplePFAS.csv` found on Quercus.
3. Using the `webchem` package, obtain the following molecular descriptors from the PubChem database:`MolecularFormula, MolecularWeight, CanonicalSMILES, IUPACName, XLogP, MonoisotopicMass, TPSA, Charge`, and `Volume3D`. 
4. Combine both your compound `data.frame` and your obtained chemical descriptors into a single data.frame and save it as a comma-separated values (csv) file. 
4. Draw your assigned chemical using it's SMILES; you can use [PubChem Sketcher](https://pubchem.ncbi.nlm.nih.gov/edit3/index.html).
5. Create a plot of *molecular weight* vs. *LogP* of the seven compounds in your dataset. *You're plot must have at least one element differing from the example plot shown in the accompanying handout*.
    - Ideas to change your plot include [applying a theme](https://ggplot2.tidyverse.org/reference/ggtheme.html), [modifying the axis labels and including a plot title](https://ggplot2.tidyverse.org/reference/labs.html)), or anything else you can think of. 
6. Discuss the results of your plot; example points of discussion are written in the accompanying handout. 
7. **Submit the entirety of your work --- code, plots, and discussion --- as a PDF written in R markdown.** to Quercus.
    - See the *R Markdown tutorial* file on Quercus for additional support.
    - A skeleton R markdown file is provided on Quercus for your convenience, you'll need to fill it in with your own code and results. 



